# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='crawl_status',
            field=models.CharField(choices=[('N', 'Not Yet'), ('Q', 'In Queue'), ('Y', 'Done')], max_length=1),
        ),
    ]
