# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0006_auto_20160902_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=400, unique=True),
        ),
    ]
