# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0007_auto_20160902_1036'),
        ('crawl', '0007_blog_coeffition'),
    ]

    operations = [
    ]
