# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0007_blog_coeffition'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reaching_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
