# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0008_blog_reaching_count'),
        ('crawl', '0008_merge'),
    ]

    operations = [
    ]
